services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/var/www
    - /var/www/vendor
    - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - 8000:8000
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:â€¦

    depends_on: 
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
  # web:
  #   image: nginx:alpine
  #   ports:
  #   - 8000:80
  #   volumes:
  #   - .:/var/www
  #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #   - app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biotrack_db
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:


